openapi: 3.0.1
info:
  title: SalesforceLeads
  description: API Definition of SalesforceLeads
  version: 1.0.0
servers:
- url: http://localhost:8290/leads
paths:
  /convertToLead:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
